"""Deterministic V1.4 portfolio optimization and program decision analytics."""

from molecule_ranker.portfolio.batch_builder import (
    build_active_learning_batch,
    build_assay_triage_batch,
    build_developability_review_batch,
    build_expert_review_batch,
    build_portfolio_batch,
    build_structure_review_batch,
)
from molecule_ranker.portfolio.candidate_builder import (
    build_candidates_from_artifacts,
    build_portfolio_candidates,
    build_portfolio_candidates_from_artifacts,
)
from molecule_ranker.portfolio.constraints import (
    collect_constraint_violations,
    constraint_allows_candidate,
    default_constraints,
    group_constraints,
)
from molecule_ranker.portfolio.diversity import (
    compute_pairwise_similarity_matrix,
    compute_portfolio_diversity,
    suggest_diversity_improvements,
)
from molecule_ranker.portfolio.objectives import (
    ObjectiveEvaluation,
    aggregate_objective_scores,
    candidate_objective_score,
    default_objectives,
    explain_objectives,
    maximize_developability,
    maximize_evidence_strength,
    maximize_experiment_readiness,
    maximize_experimental_followup_value,
    maximize_learning_value,
    maximize_mechanism_diversity,
    maximize_scaffold_diversity,
    maximize_target_coverage,
    minimize_correlated_risk,
    minimize_generated_overexposure,
)
from molecule_ranker.portfolio.optimizer import PortfolioOptimizer, optimize_portfolio
from molecule_ranker.portfolio.reports import (
    generate_program_decision_memo,
    render_decision_memo_markdown,
    render_portfolio_report_markdown,
    validate_memo_guardrails,
    write_portfolio_report,
    write_program_decision_memo,
)
from molecule_ranker.portfolio.risk import (
    compute_risk_concentration,
    identify_correlated_risks,
)
from molecule_ranker.portfolio.scenarios import (
    apply_scenario_to_portfolio,
    build_decision_scenario,
    compare_decision_scenarios,
    default_scenarios,
)
from molecule_ranker.portfolio.schemas import (
    DecisionScenario,
    Portfolio,
    PortfolioBatch,
    PortfolioCandidate,
    PortfolioConstraint,
    PortfolioObjective,
    PortfolioOptimizationRun,
    PortfolioSelection,
    Program,
    ProgramDecisionMemo,
    ResourceBudget,
    SensitivityAnalysis,
    StageGate,
)

__all__ = [
    "DecisionScenario",
    "Portfolio",
    "PortfolioBatch",
    "PortfolioCandidate",
    "ObjectiveEvaluation",
    "PortfolioConstraint",
    "PortfolioObjective",
    "PortfolioOptimizationRun",
    "PortfolioOptimizer",
    "PortfolioSelection",
    "Program",
    "ProgramDecisionMemo",
    "ResourceBudget",
    "SensitivityAnalysis",
    "StageGate",
    "aggregate_objective_scores",
    "apply_scenario_to_portfolio",
    "build_active_learning_batch",
    "build_assay_triage_batch",
    "build_candidates_from_artifacts",
    "build_decision_scenario",
    "build_developability_review_batch",
    "build_expert_review_batch",
    "build_portfolio_candidates_from_artifacts",
    "build_portfolio_candidates",
    "build_portfolio_batch",
    "build_structure_review_batch",
    "candidate_objective_score",
    "collect_constraint_violations",
    "compare_decision_scenarios",
    "compute_pairwise_similarity_matrix",
    "compute_portfolio_diversity",
    "compute_risk_concentration",
    "constraint_allows_candidate",
    "default_constraints",
    "default_objectives",
    "default_scenarios",
    "explain_objectives",
    "generate_program_decision_memo",
    "group_constraints",
    "identify_correlated_risks",
    "maximize_developability",
    "maximize_evidence_strength",
    "maximize_experiment_readiness",
    "maximize_experimental_followup_value",
    "maximize_learning_value",
    "maximize_mechanism_diversity",
    "maximize_scaffold_diversity",
    "maximize_target_coverage",
    "minimize_correlated_risk",
    "minimize_generated_overexposure",
    "optimize_portfolio",
    "render_decision_memo_markdown",
    "render_portfolio_report_markdown",
    "suggest_diversity_improvements",
    "validate_memo_guardrails",
    "write_program_decision_memo",
    "write_portfolio_report",
]
