"""V1.5 cross-program knowledge graph and mechanism-level reasoning."""

from molecule_ranker.knowledge_graph.builder import GraphBuilder
from molecule_ranker.knowledge_graph.codex_assistant import (
    CodexGraphAssistant,
    GraphCodexArtifact,
    detect_graph_guardrail_violations,
)
from molecule_ranker.knowledge_graph.contradiction import (
    ContradictionReport,
    StalenessReport,
    build_contradiction_report,
    build_staleness_report,
    detect_contradiction_relations,
    detect_staleness_relations,
)
from molecule_ranker.knowledge_graph.dashboard import (
    render_knowledge_graph_dashboard_html,
    write_knowledge_graph_dashboard,
)
from molecule_ranker.knowledge_graph.export import (
    GraphExportFormat,
    export_graph,
    export_graph_csv,
    export_graph_graphml,
    export_graph_json,
    export_graph_turtle,
    sanitized_graph_payload,
)
from molecule_ranker.knowledge_graph.mechanism import extract_mechanism_hypotheses
from molecule_ranker.knowledge_graph.ontology import IdentifierMapper, normalize_identifier
from molecule_ranker.knowledge_graph.reasoning import (
    GraphEntityRef,
    GraphQueryResult,
    GraphReasoner,
    GraphRelationRef,
    analyze_cross_program_knowledge,
    candidates_for_target,
    candidates_with_contradictory_evidence,
    evidence_gaps_for_candidate,
    generated_molecules_without_direct_evidence,
    graph_paths_between_disease_and_molecule,
    mechanisms_for_disease,
    mechanisms_supported_across_programs,
    molecules_with_safety_concerns_across_programs,
    portfolios_reusing_same_scaffold_risk,
    projects_with_stale_model_predictions,
    scaffolds_with_positive_assay_history,
    targets_with_repeated_developability_failures,
)
from molecule_ranker.knowledge_graph.recommendations import (
    generate_graph_recommendations,
    recommend_from_graph,
)
from molecule_ranker.knowledge_graph.schemas import (
    CrossProgramAnalysis,
    GraphBuildRun,
    GraphEntity,
    GraphFinding,
    GraphPattern,
    GraphProvenance,
    GraphRecommendation,
    GraphRelation,
    GraphValidationReport,
    KnowledgeGraph,
    MechanismHypothesis,
    ProvenanceSource,
    TargetPattern,
)
from molecule_ranker.knowledge_graph.store import KnowledgeGraphStore
from molecule_ranker.knowledge_graph.validation import validate_knowledge_graph

__all__ = [
    "CodexGraphAssistant",
    "ContradictionReport",
    "CrossProgramAnalysis",
    "GraphBuilder",
    "GraphBuildRun",
    "GraphCodexArtifact",
    "GraphEntity",
    "GraphEntityRef",
    "GraphExportFormat",
    "GraphFinding",
    "GraphPattern",
    "GraphProvenance",
    "GraphQueryResult",
    "GraphRecommendation",
    "GraphRelation",
    "GraphRelationRef",
    "GraphReasoner",
    "GraphValidationReport",
    "IdentifierMapper",
    "KnowledgeGraph",
    "KnowledgeGraphStore",
    "MechanismHypothesis",
    "ProvenanceSource",
    "StalenessReport",
    "TargetPattern",
    "analyze_cross_program_knowledge",
    "build_contradiction_report",
    "build_staleness_report",
    "candidates_for_target",
    "candidates_with_contradictory_evidence",
    "detect_contradiction_relations",
    "detect_graph_guardrail_violations",
    "detect_staleness_relations",
    "evidence_gaps_for_candidate",
    "export_graph",
    "export_graph_csv",
    "export_graph_graphml",
    "export_graph_json",
    "export_graph_turtle",
    "extract_mechanism_hypotheses",
    "generated_molecules_without_direct_evidence",
    "generate_graph_recommendations",
    "graph_paths_between_disease_and_molecule",
    "mechanisms_for_disease",
    "mechanisms_supported_across_programs",
    "molecules_with_safety_concerns_across_programs",
    "normalize_identifier",
    "portfolios_reusing_same_scaffold_risk",
    "projects_with_stale_model_predictions",
    "render_knowledge_graph_dashboard_html",
    "recommend_from_graph",
    "sanitized_graph_payload",
    "scaffolds_with_positive_assay_history",
    "targets_with_repeated_developability_failures",
    "validate_knowledge_graph",
    "write_knowledge_graph_dashboard",
]
