# pyright: reportUnsupportedDunderAll=false

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES = {
    "FilesystemAccessLevel": "molecule_ranker.tool_ecosystem.policy",
    "FilesystemPolicy": "molecule_ranker.tool_ecosystem.sandbox",
    "InternalMCPGateway": "molecule_ranker.tool_ecosystem.mcp_gateway",
    "MCPAdapterError": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPGatewayContext": "molecule_ranker.tool_ecosystem.mcp_gateway",
    "MCPGatewayResult": "molecule_ranker.tool_ecosystem.mcp_gateway",
    "MCPIntrospectionResult": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPPromptDescriptor": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPResourceDescriptor": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPServerAdapter": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPServerConfig": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPServerStatus": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPServerTransport": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MCPToolDescriptor": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "MarketplaceError": "molecule_ranker.tool_ecosystem.marketplace",
    "MarketplacePackageState": "molecule_ranker.tool_ecosystem.marketplace",
    "MarketplaceUsageAnalytics": "molecule_ranker.tool_ecosystem.marketplace",
    "NetworkAccessLevel": "molecule_ranker.tool_ecosystem.policy",
    "SandboxProfileError": "molecule_ranker.tool_ecosystem.sandbox",
    "SkillPack": "molecule_ranker.tool_ecosystem.schemas",
    "SkillPackExpansionError": "molecule_ranker.tool_ecosystem.skills",
    "SkillStepTemplate": "molecule_ranker.tool_ecosystem.skills",
    "ToolApproval": "molecule_ranker.tool_ecosystem.schemas",
    "ToolApprovalStatus": "molecule_ranker.tool_ecosystem.schemas",
    "ToolEcosystemSchema": "molecule_ranker.tool_ecosystem.schemas",
    "ToolEcosystemSkill": "molecule_ranker.tool_ecosystem.skills",
    "ToolManifest": "molecule_ranker.tool_ecosystem.schemas",
    "ToolMarketplace": "molecule_ranker.tool_ecosystem.marketplace",
    "ToolPackage": "molecule_ranker.tool_ecosystem.schemas",
    "ToolPackageSource": "molecule_ranker.tool_ecosystem.schemas",
    "ToolPackageStatus": "molecule_ranker.tool_ecosystem.schemas",
    "ToolPackageType": "molecule_ranker.tool_ecosystem.schemas",
    "ToolPolicyConfig": "molecule_ranker.tool_ecosystem.policy",
    "ToolPolicyContext": "molecule_ranker.tool_ecosystem.policy",
    "ToolPolicyDecision": "molecule_ranker.tool_ecosystem.policy",
    "ToolPolicyDecisionStatus": "molecule_ranker.tool_ecosystem.policy",
    "ToolPolicyEngine": "molecule_ranker.tool_ecosystem.policy",
    "ToolRegistryV2": "molecule_ranker.tool_ecosystem.registry",
    "ToolRegistryV2Error": "molecule_ranker.tool_ecosystem.registry",
    "ToolRiskLevel": "molecule_ranker.tool_ecosystem.schemas",
    "ToolSandboxProfile": "molecule_ranker.tool_ecosystem.sandbox",
    "ToolSandboxProfileName": "molecule_ranker.tool_ecosystem.sandbox",
    "ToolSecurityFinding": "molecule_ranker.tool_ecosystem.security",
    "ToolSecurityScan": "molecule_ranker.tool_ecosystem.schemas",
    "ToolSecurityScanStatus": "molecule_ranker.tool_ecosystem.schemas",
    "ToolSecurityScannerConfig": "molecule_ranker.tool_ecosystem.security",
    "ToolUsageInvoker": "molecule_ranker.tool_ecosystem.schemas",
    "ToolUsageRecord": "molecule_ranker.tool_ecosystem.schemas",
    "ToolVersion": "molecule_ranker.tool_ecosystem.schemas",
    "ToolVersionStatus": "molecule_ranker.tool_ecosystem.schemas",
    "WorkflowTemplate": "molecule_ranker.tool_ecosystem.schemas",
    "default_sandbox_profile": "molecule_ranker.tool_ecosystem.sandbox",
    "expand_skill_to_plan": "molecule_ranker.tool_ecosystem.skills",
    "filesystem_access_level": "molecule_ranker.tool_ecosystem.policy",
    "generate_codex_permission_profile_snippet": "molecule_ranker.tool_ecosystem.sandbox",
    "get_builtin_skill": "molecule_ranker.tool_ecosystem.skills",
    "get_builtin_skill_pack": "molecule_ranker.tool_ecosystem.skills",
    "get_sandbox_profile": "molecule_ranker.tool_ecosystem.sandbox",
    "hash_manifest": "molecule_ranker.tool_ecosystem.registry",
    "hash_schema": "molecule_ranker.tool_ecosystem.registry",
    "has_blocking_findings": "molecule_ranker.tool_ecosystem.security",
    "is_namespace_qualified": "molecule_ranker.tool_ecosystem.registry",
    "list_builtin_skill_packs": "molecule_ranker.tool_ecosystem.skills",
    "list_builtin_skills": "molecule_ranker.tool_ecosystem.skills",
    "mcp_tool_to_runtime_spec": "molecule_ranker.tool_ecosystem.mcp_adapter",
    "network_access_level": "molecule_ranker.tool_ecosystem.policy",
    "profile_for_tool": "molecule_ranker.tool_ecosystem.sandbox",
    "scan_tool_package": "molecule_ranker.tool_ecosystem.security",
    "validate_skill_pack": "molecule_ranker.tool_ecosystem.skills",
}

__all__ = [
    "FilesystemAccessLevel",
    "FilesystemPolicy",
    "InternalMCPGateway",
    "MCPAdapterError",
    "MCPGatewayContext",
    "MCPGatewayResult",
    "MCPIntrospectionResult",
    "MCPPromptDescriptor",
    "MCPResourceDescriptor",
    "MCPServerAdapter",
    "MCPServerConfig",
    "MCPServerStatus",
    "MCPServerTransport",
    "MCPToolDescriptor",
    "MarketplaceError",
    "MarketplacePackageState",
    "MarketplaceUsageAnalytics",
    "NetworkAccessLevel",
    "SandboxProfileError",
    "SkillPack",
    "SkillPackExpansionError",
    "SkillStepTemplate",
    "ToolApproval",
    "ToolApprovalStatus",
    "ToolEcosystemSchema",
    "ToolEcosystemSkill",
    "ToolManifest",
    "ToolMarketplace",
    "ToolPackage",
    "ToolPackageSource",
    "ToolPackageStatus",
    "ToolPackageType",
    "ToolPolicyConfig",
    "ToolPolicyContext",
    "ToolPolicyDecision",
    "ToolPolicyDecisionStatus",
    "ToolPolicyEngine",
    "ToolRegistryV2",
    "ToolRegistryV2Error",
    "ToolRiskLevel",
    "ToolSandboxProfile",
    "ToolSandboxProfileName",
    "ToolSecurityFinding",
    "ToolSecurityScan",
    "ToolSecurityScanStatus",
    "ToolSecurityScannerConfig",
    "ToolUsageInvoker",
    "ToolUsageRecord",
    "ToolVersion",
    "ToolVersionStatus",
    "WorkflowTemplate",
    "default_sandbox_profile",
    "expand_skill_to_plan",
    "filesystem_access_level",
    "generate_codex_permission_profile_snippet",
    "get_builtin_skill",
    "get_builtin_skill_pack",
    "get_sandbox_profile",
    "has_blocking_findings",
    "hash_manifest",
    "hash_schema",
    "is_namespace_qualified",
    "list_builtin_skill_packs",
    "list_builtin_skills",
    "mcp_tool_to_runtime_spec",
    "network_access_level",
    "profile_for_tool",
    "scan_tool_package",
    "validate_skill_pack",
]


def __getattr__(name: str) -> Any:
    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError as exc:
        raise AttributeError(name) from exc
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
